### ISSUE TITLE
Latest logs are not displayed until quitting

### ISSUE THREAD

**Issue by tamirzb** [yan12125/logcat-color3#3]
When running live (i.e. without `--dump`) logcat-color3 doesn't display the latest log messages (usually between around 1-2 lines I think). When I run the original logcat-color along with logcat-color3, I can see that the original one is always a few steps ahead. When I close logcat-color3 by pressing Ctrl+C I can see that it actually prints the latest log messages that it didn't print before and then quits.

**Comment by yan12125** [comment]
Seems a python3-specific issue. logcat-color3 0.9.0 running on python2 goes faster than 0.9.0 on python3, too.

**Comment by yan12125** [comment]
The issue should be fixed with the latest git commit. Feel free to open a new issue if something is still wrong, thanks!

I will try to release a new version soon. First, I need to check out how to sign releases after [PyPI dropped PGP support](https://blog.pypi.org/posts/2023-05-23-removing-pgp/).
